#!/bin/sh

#Mounts the noobs Data_Partition at the folder location given by the first argument.
#If no argument is given, it mounts the data partition at /mnt/DATA

#Get the NOOBS setting partition
sudo mkdir -p /media/SETTINGS
sudo mount /dev/mmcblk0p3 /media/SETTINGS

if [ "$1" ]; then
    MyData="$1"
else
    MyData="/mnt/DATA"
fi

while read line
do
	name=`echo $line | sed -n "s/\"name\".*:.*\"\(.*\)\".*/\1\r\n/p" | sed "s/ \+/_/g" | tr -d '\r'`
	if [ "$name" ]; then
		partname=$name
	fi
	name=`echo $line | sed -n "s/\"partitions\"/partitions/p"`
	if [ "$name" ]; then
		read line
		if [ "$partname" = "Data_Partition" ]; then
			data_part=`echo $line | sed -n "s/\"\(.*\)\"/\1/p"`
		fi
		read line 
		#end=`echo $line | sed -n "s/]/]/p"`
	fi
done </media/SETTINGS/installed_os.json

sudo umount /media/SETTINGS
sudo rmdir /media/SETTINGS

if [ "$data_part" ]; then
    echo "$data_part $MyData ext4 defaults 0 0" | sudo tee -a /etc/fstab >/dev/null
	sudo mkdir -p "$MyData"
	sudo mount "$data_part" "$MyData" -t ext4
fi
